version: "3.9"
services:
  db:
    image: postgres:15
    container_name: earn_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: earn_launchpad
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: earn_backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/earn_launchpad?schema=public
    depends_on:
      - db
    volumes:
      - ./api:/app
    command: npm run dev

volumes:
  db_data:
